[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "mypkg"
version = "0.1"

dependencies = ["numpy"]

[tool.pytest.ini_options]
pythonpath = [
  ".", "mypkg"
]

